name: Build mod

on: [ push, pull_request ]

jobs:
  build:
    name: Build mod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: 25
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --no-daemon --stacktrace build
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: aqua-acrobatics
        path: |
          build/libs/AquaAcrobatics-*.jar
          !build/libs/AquaAcrobatics-*-*.jar
        archive: false
